name: gdrivecms
description: Flutter Google Drive CMS.

publish_to: "none"

version: 0.9.0

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.3

  google_fonts: ^2.1.0
  flutter_svg: ^0.23.0+1
  fl_chart: ^0.36.1
  provider: ^6.0.0
  data_table_2: ^2.0.3
  intl: ^0.17.0

  flutter_html: ^2.2.1
  flutter_math_fork: ^0.5.0
  hooks_riverpod: ^1.0.3

  google_sign_in: ^5.4.2
  google_sign_in_web: ^0.10.2
  flutter_secure_storage: ^5.0.2
  googleapis: ^9.2.0
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true


